### ISSUE TITLE
getting NULL while date choose from calendar Icon, after selection month filled only 8 instead of 08

### ISSUE THREAD

**Issue by avnp16** [AnthonyAniobi/Date_Format_Field#2]
getting NULL while date choose from calendar Icon, after selection month filled only 8 instead of 08,

issue for month selection in 1 to 9 , for single digit, it should be filled 09 as per your format

**Comment by AnthonyAniobi** [comment]
This issue has been fixed in the new version `0.0.5`
Thanks for pointing this out.

**Comment by avnp16** [comment]
Great
