### ISSUE TITLE
Getting Null as date while selecting date from Icon ( Date picker)

### ISSUE THREAD

**Issue by avnp16** [AnthonyAniobi/Date_Format_Field#4]
Getting Null as the date while selecting a date from Icon ( Date picker), works only when we type we fill date after typing...but while choose and pick date from calender icon, getting NULL, pls resolve the issue as soon as possible, Bcoz We have user this package in live production.

**Comment by AnthonyAniobi** [comment]
Thanks @avnp16. 
I just implemented this change, 
I am glad this package is used in production, I would make sure to keep all bugs out of all updates

**Comment by avnp16** [comment]
Ohh ! Greate .. THANKS FOR VERY QUICK RESOLVE

**Comment by avnp16** [comment]
Ohh ! Greate .. THANKS FOR VERY QUICK RESOLVE
